"""create tables

Revision ID: f6181c47244d
Revises: c776a83f9d4e
Create Date: 2026-01-27 19:23:35.942312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6181c47244d'
down_revision: Union[str, Sequence[str], None] = 'c776a83f9d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('offer_type', sa.String(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('influencers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('profile_url', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Numeric(), nullable=True),
    sa.Column('niche_tags', sa.JSON(), nullable=True),
    sa.Column('brand_fit_score', sa.Numeric(), nullable=True),
    sa.Column('risk_score', sa.Numeric(), nullable=True),
    sa.Column('overall_score', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_influencers_handle'), 'influencers', ['handle'], unique=False)
    op.create_table('outreach_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('influencer_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('deal_terms', sa.JSON(), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(), nullable=True),
    sa.Column('next_followup_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('provider_msg_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['outreach_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('outreach_threads')
    op.drop_index(op.f('ix_influencers_handle'), table_name='influencers')
    op.drop_table('influencers')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
